version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Setting up the python environment..."
      - make prepare
      - python3.8 -m venv venv
      - source venv/bin/activate
      - make install
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Executing linting..."
      - make lint
      - echo "Executing tests and generating the models..."
      - make test
  build:
    commands:
      - echo "Building the docker image..."
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo "Pushing the docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      
artifacts:
  files:
    - Dockerrun.aws.json